# Generated by Django 5.0.3 on 2024-03-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=30)),
                ('product_description', models.TextField()),
                ('product_manufacture_year', models.PositiveIntegerField(blank=True)),
                ('product_base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_verify', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(blank=True, upload_to='product_images/')),
            ],
        ),
    ]
