# Generated by Django 5.0.3 on 2024-03-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllBids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='AuctionDetails',
            fields=[
                ('auction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('auction_date', models.DateField(blank=True)),
                ('auctio_start_time', models.TimeField(blank=True)),
                ('auctio_end_time', models.TimeField(blank=True)),
                ('increment_amount', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AutomaticBidding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_bid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('inc_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Bidders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidder_type', models.CharField(choices=[('automatic', 'automatic'), ('manual', 'manual')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ClosingBids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing_bid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentAuctions',
            fields=[
                ('current_auction_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentBids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transaction_status', models.BooleanField(default=False)),
            ],
        ),
    ]
