# Generated by Django 5.0.3 on 2024-03-13 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AuctionApp', '0001_initial'),
        ('SellerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctiondetails',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='SellerApp.product'),
        ),
        migrations.AddField(
            model_name='allbids',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allauctionbids', to='AuctionApp.auctiondetails'),
        ),
        migrations.AddField(
            model_name='automaticbidding',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_autobids', to='AuctionApp.auctiondetails'),
        ),
    ]
