# Generated by Django 5.0.3 on 2024-03-13 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AuctionApp', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bidders',
            name='bidder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bidders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='automaticbidding',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autobids', to='AuctionApp.bidders'),
        ),
        migrations.AddField(
            model_name='allbids',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allbids', to='AuctionApp.bidders'),
        ),
        migrations.AddField(
            model_name='closingbids',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closing_auctions', to='AuctionApp.auctiondetails'),
        ),
        migrations.AddField(
            model_name='closingbids',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closing_bids', to='AuctionApp.bidders'),
        ),
        migrations.AddField(
            model_name='currentauctions',
            name='auction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_auction', to='AuctionApp.auctiondetails'),
        ),
        migrations.AddField(
            model_name='currentbids',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_bids', to='AuctionApp.currentauctions'),
        ),
        migrations.AddField(
            model_name='currentbids',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_bids', to='AuctionApp.bidders'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to=settings.AUTH_USER_MODEL),
        ),
    ]
