# Generated by Django 5.0.3 on 2024-03-13 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AuctionApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auctions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_wishlist', to='AuctionApp.auctiondetails')),
            ],
        ),
    ]
