# Generated by Django 5.0.3 on 2024-03-13 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AuctionApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelledAuctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancellation_reason', models.TextField()),
                ('cancelled_by', models.CharField(choices=[('owner', 'owner'), ('admin', 'admin')], max_length=10)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_auction', to='AuctionApp.auctiondetails')),
            ],
        ),
        migrations.CreateModel(
            name='SuccessAuctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='AuctionApp.auctiondetails')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_bidder', to='AuctionApp.bidders')),
            ],
        ),
    ]
